name: Android build APK

on:
  push:
    branches:
      - main  # Hoặc branch mặc định của bạn (e.g., master, develop)
  pull_request:
    branches:
      - main  # Hoặc branch mặc định của bạn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.6.12' # Hoặc phiên bản Flutter cụ thể (e.g., 3.7.12)
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
